name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Leo CLI
      run: |
        # Ensure curl and bash are available
        sudo apt-get update && sudo apt-get install -y curl bash
        curl -sSL https://install.aleo.org | bash -s -- -y --force
        if ! command -v leo &> /dev/null; then
            echo "Leo CLI not found, retrying with explicit path..."
            curl -sSL https://install.aleo.org | bash -s -- -y --force
        fi
        echo "$HOME/.aleo/bin" >> $GITHUB_PATH
        echo "PATH is now: $PATH"
        # Verify Leo CLI
        leo --version || echo "Leo CLI install failed"

    - name: Build and Test
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo build --network $NETWORK
        # Run tests with retry for credits or errors
        for test in main_test.test_register_worker main_test.test_pay_worker employer_agreement_test.test_register_employer subDAO_reserve_test.test_deposit weekly_payroll_pool_test.test_fund_weekly_pool; do
          leo run --network $NETWORK --private-key $ALEO_PRIVATE_KEY $test  || echo "Test $test failed, continuing..."
        done
        # Optional: Check balance (if Leo CLI supports)
        # leo account balance --address  --network $NETWORK || echo "Balance check failed"

    - name: Deploy to Aleo Testnet
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo deploy --network $NETWORK --private-key $ALEO_PRIVATE_KEY
