name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Leo CLI
      run: |
        curl -sSL https://install.aleo.org | bash -s -- -y
        if ! command -v leo &> /dev/null; then
            echo "Leo CLI not found, retrying install..."
            curl -sSL https://install.aleo.org | bash -s -- -y
        fi
        echo "$HOME/.aleo/bin" >> $GITHUB_PATH
        echo "PATH is now: $PATH"

    - name: Build and Test
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo build --network $NETWORK
        leo run --network $NETWORK main_test.test_register_worker
        leo run --network $NETWORK main_test.test_pay_worker aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk aleo1employer1234567890example

    - name: Deploy to Aleo Testnet
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo deploy --network $NETWORK --private-key $ALEO_PRIVATE_KEY
