name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Leo CLI
      run: |
        curl -sSL https://install.aleo.org | bash -s -- -y
        echo "$HOME/.aleo/bin" >> $GITHUB_PATH

    - name: Build and Test
      env:
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo build
        # Test key transitions with your test addresses
        leo run --network testnet --private-key $ALEO_PRIVATE_KEY main_test.test_register_worker
        leo run --network testnet --private-key $ALEO_PRIVATE_KEY employer_agreement_test.test_register_employer
        leo run --network testnet --private-key $ALEO_PRIVATE_KEY subDAO_reserve_test.test_deposit aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk
        leo run --network testnet --private-key $ALEO_PRIVATE_KEY weekly_payroll_pool_test.test_fund_weekly_pool aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk

    - name: Deploy to Aleo Testnet
      env:
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo deploy --network testnet --private-key $ALEO_PRIVATE_KEY
