name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl jq

      - name: Download and Install Leo CLI
        run: |
          curl -L -o leo.zip https://github.com/PNWBNW/PNW_MVP/releases/download/leo-2.4.1/leo-mainnet-x86_64-unknown-linux-gnu.zip
          unzip leo.zip
          sudo mv leo /usr/local/bin/leo
          sudo chmod +x /usr/local/bin/leo
          leo --version

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build PNW_MVP Project
        run: |
          leo clean
          leo build --network testnet

      - name: Deploy to Aleo Testnet
        env:
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
        run: |
          if [ ! -f program.json ]; then
            echo "Error: program.json not found!"
            exit 1
          fi

          PROGRAMS=$(jq -r '.programs[].program' program.json)

          if [ -z "$PROGRAMS" ]; then
            echo "Error: No programs found in program.json!"
            exit 1
          fi

          for PROGRAM in $PROGRAMS; do
            echo "Deploying $PROGRAM..."
            leo deploy "$PROGRAM" --private-key="$ALEO_PRIVATE_KEY" --network testnet || {
              echo "Deployment of $PROGRAM failed: $?"
              exit 1
            }
          done
