name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl jq  # jq added for JSON parsing

      - name: Download and Extract Leo Binary
        run: |
          set -e
          echo "Downloading Leo CLI..."
          curl -L -o leo.zip https://github.com/PNWBNW/PNW_MVP/releases/download/leo-2.4.1/leo-mainnet-x86_64-unknown-linux-gnu.zip
          
          echo "Extracting Leo CLI..."
          unzip leo.zip
          
          echo "Searching for Leo binary..."
          LEO_PATH=$(find . -type f -name "leo" | head -n 1)
          if [ -z "$LEO_PATH" ]; then
            echo "Error: Leo binary not found!"
            exit 1
          fi
          
          echo "Found Leo binary at: $LEO_PATH"
          echo "Moving Leo binary to /usr/local/bin..."
          sudo mv "$LEO_PATH" /usr/local/bin/leo
          sudo chmod +x /usr/local/bin/leo
          
          echo "Verifying Leo CLI installation..."
          /usr/local/bin/leo --version

      - name: Cache Rust & Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Clean & Build PNW_MVP Project
        run: |
          leo clean
          leo build --network testnet

      - name: Deploy to Aleo Testnet
        env:
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
        run: |
          echo "Checking if program.json exists..."
          if [ ! -f program.json ]; then
            echo "Error: program.json not found!"
            exit 1
          fi
          
          echo "Extracting program names from program.json..."
          PROGRAMS=$(jq -r '.programs[].program | sub("src/"; "") | sub(".leo$"; "")' program.json)
          
          if [ -z "$PROGRAMS" ]; then
            echo "Error: No programs found in program.json!"
            exit 1
          fi
          
          for PROGRAM in $PROGRAMS; do
            echo "Deploying $PROGRAM..."
            leo deploy "pnw_mvp" --private-key="${{ secrets.ALEO_PRIVATE_KEY }}" --network testnet || exit 1
          done
