name: Deploy Aleo Contract

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libssl-dev

      - name: Install Leo
        run: cargo install leo-lang

      - name: Build project
        run: leo build

      - name: Deploy contract
        env:
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
        run: |
          if [ -z "$ALEO_PRIVATE_KEY" ]; then
            echo "Error: ALEO_PRIVATE_KEY is not set."
            exit 1
          fi
          leo deploy --private-key "$ALEO_PRIVATE_KEY" --query

      - name: Run tests
        run: leo test
