name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Leo CLI
      run: |
        curl -sSL https://install.aleo.org | bash -s -- -y
        if ! command -v leo &> /dev/null; then
            echo "Leo CLI not found, retrying install..."
            curl -sSL https://install.aleo.org | bash -s -- -y
        fi
        echo "$HOME/.aleo/bin" >> $GITHUB_PATH
        echo "PATH is now: $PATH"

    - name: Build and Test
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo build --network $NETWORK
        # Test key transitions with your test addresses
        leo run --network $NETWORK main_test.test_register_worker
        leo run --network $NETWORK main_test.test_pay_worker aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk aleo1employer1234567890example
        leo run --network $NETWORK employer_agreement_test.test_register_employer
        leo run --network $NETWORK employer_agreement_test.test_verify_employer_tax
        leo run --network $NETWORK employer_agreement_test.test_fund_payroll_pool aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk
        leo run --network $NETWORK subDAO_reserve_test.test_deposit aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk
        leo run --network $NETWORK subDAO_reserve_test.test_process_taxes aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk
        leo run --network $NETWORK weekly_payroll_pool_test.test_fund_weekly_pool aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk
        leo run --network $NETWORK weekly_payroll_pool_test.test_execute_weekly_payroll aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk 100u64
        # Optional: Check balances on testnet (if Leo CLI supports)
        # leo account balance --address aleo1zay2jaxzyrsued32g3hmkfxr9apsaj8cjmwa9j68vrtlem5e5yys4yruyk --network $NETWORK

    - name: Deploy to Aleo Testnet
      env:
        NETWORK: testnet
        ALEO_PRIVATE_KEY: ${{ secrets.Aleo_test_key }}
      run: |
        leo deploy --network $NETWORK --private-key $ALEO_PRIVATE_KEY
