name: Deploy to Aleo Testnet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Rust & Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust (Only If Not Cached)
        run: |
          rustc --version || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version

      - name: Ensure 'tar' and 'curl' Are Installed
        run: sudo apt-get update && sudo apt-get install -y tar curl

      - name: Download and Install Leo 2.4.1
        run: |
          set -e
          echo "Downloading leo-2.4.1.tar.gz..."
          curl -L -o leo.tar.gz https://github.com/PNWBNW/PNW_MVP/releases/download/leo-2.4.1/leo-2.4.1.tar.gz
          echo "Download completed."

          echo "Verifying the downloaded file..."
          file leo.tar.gz
          tar -tzf leo.tar.gz
          echo "Verification completed."

          echo "Extracting leo.tar.gz..."
          mkdir -p leo_extracted
          tar -xzf leo.tar.gz -C leo_extracted
          echo "Extraction completed."

          echo "Listing extracted files..."
          ls -l leo_extracted
          echo "Listed extracted files."

          echo "Installing Leo binary..."
          sudo mv leo_extracted/leo /usr/local/bin/leo
          sudo chmod +x /usr/local/bin/leo
          echo "Installation completed."

          echo "Verifying Leo installation..."
          /usr/local/bin/leo --version
          echo "Leo version displayed."

      - name: Clean and Build Project
        run: |
          leo clean
          leo build

      - name: Deploy to Aleo Testnet
        env:
          ALEO_PRIVATE_KEY: ${{ secrets.ALEO_PRIVATE_KEY }}
        run: |
          leo deploy --private-key="${{ secrets.ALEO_PRIVATE_KEY }}" --network testnet
